server.port=${PORT:8080}

spring.application.name=vault-map-integration
server.servlet.context-path=/vault-integration

# Logging Configuration
logging.level.com.veeva.vault.integration=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html