# Spring Boot Configuration
server.port=${PORT:8080}

spring.application.name=vault-map-integration
server.servlet.context-path=/vault-integration

# Vault Configuration
vault.api.url=https://mssandbox-chintan.veevavault.com/api
vault.api.version=v25.3

# Logging Configuration
logging.level.com.veeva.vault.integration=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# HTTP Client Configuration
spring.http.client.connect-timeout=30000
spring.http.client.read-timeout=60000

 #SSL Configuration
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=mycert
#server.ssl.trust-store=file:C:/certs/truststore.jks

# Actuator Configuration
management.endpoints.web.exposure.include=*